name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

    - name: Login to Github Container Registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
    
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/${{ github.repository }}:latest

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest
